require("colout.plugins-setup")
require("colout.core.options")
require("colout.core.keymaps")
require("colout.core.colorscheme")

require("colout.plugins.nvim-tree")
require("colout.plugins.lualine")
require("colout.plugins.telescope")
require("colout.plugins.nvim-cmp")
require("colout.plugins.lsp.mason")
require("colout.plugins.lsp.lspsaga")
require("colout.plugins.lsp.lspconfig")
require("colout.plugins.lsp.null-ls")
require("colout.plugins.autopairs")
require("colout.plugins.treesitter")
require("colout.plugins.gitsigns")
require("colout.plugins.terraform")
